export const mufftiProducts = [
  {
    id: 381,
    name: "Muffti Casual Shirt 1",
    price: 1499,
    image: "https://via.placeholder.com/200x250?text=Muffti+Shirt+1",
    description: "Stylish casual shirt for men.",
    brand: "Muffti",
  },
  {
    id: 382,
    name: "Muffti Casual Shirt 2",
    price: 1699,
    image: "https://via.placeholder.com/200x250?text=Muffti+Shirt+2",
    description: "Comfortable cotton shirt for outings.",
    brand: "Muffti",
  },
  {
    id: 383,
    name: "Muffti Denim Jacket 1",
    price: 2599,
    image: "https://via.placeholder.com/200x250?text=Muffti+Jacket+1",
    description: "Trendy denim jacket with rugged style.",
    brand: "Muffti",
  },
  {
    id: 384,
    name: "Muffti Denim Jacket 2",
    price: 2799,
    image: "https://via.placeholder.com/200x250?text=Muffti+Jacket+2",
    description: "Modern fit denim jacket for men.",
    brand: "Muffti",
  },
  {
    id: 385,
    name: "Muffti Polo T-Shirt 1",
    price: 899,
    image: "https://via.placeholder.com/200x250?text=Muffti+Polo+1",
    description: "Classic cotton polo t-shirt.",
    brand: "Muffti",
  },
  {
    id: 386,
    name: "Muffti Polo T-Shirt 2",
    price: 999,
    image: "https://via.placeholder.com/200x250?text=Muffti+Polo+2",
    description: "Soft breathable fabric, casual wear.",
    brand: "Muffti",
  },
  {
    id: 387,
    name: "Muffti Jeans Slim Fit 1",
    price: 1999,
    image: "https://via.placeholder.com/200x250?text=Muffti+Jeans+1",
    description: "Slim fit stretchable denim jeans.",
    brand: "Muffti",
  },
  {
    id: 388,
    name: "Muffti Jeans Slim Fit 2",
    price: 2199,
    image: "https://via.placeholder.com/200x250?text=Muffti+Jeans+2",
    description: "Modern slim fit denim trousers.",
    brand: "Muffti",
  },
  {
    id: 389,
    name: "Muffti Leather Belt 1",
    price: 649,
    image: "https://via.placeholder.com/200x250?text=Muffti+Belt+1",
    description: "Premium leather belt with matte buckle.",
    brand: "Muffti",
  },
  {
    id: 390,
    name: "Muffti Leather Belt 2",
    price: 699,
    image: "https://via.placeholder.com/200x250?text=Muffti+Belt+2",
    description: "Durable leather belt for formal & casual.",
    brand: "Muffti",
  },
  {
    id: 391,
    name: "Muffti Hoodie 1",
    price: 1799,
    image: "https://via.placeholder.com/200x250?text=Muffti+Hoodie+1",
    description: "Warm hoodie with comfortable fit.",
    brand: "Muffti",
  },
  {
    id: 392,
    name: "Muffti Hoodie 2",
    price: 1899,
    image: "https://via.placeholder.com/200x250?text=Muffti+Hoodie+2",
    description: "Trendy hoodie for winter wear.",
    brand: "Muffti",
  },
  {
    id: 393,
    name: "Muffti Sneakers 1",
    price: 2799,
    image: "https://via.placeholder.com/200x250?text=Muffti+Sneakers+1",
    description: "Stylish high-top sneakers for street style.",
    brand: "Muffti",
  },
  {
    id: 394,
    name: "Muffti Sneakers 2",
    price: 2999,
    image: "https://via.placeholder.com/200x250?text=Muffti+Sneakers+2",
    description: "Comfortable sneakers for daily wear.",
    brand: "Muffti",
  },
  {
    id: 395,
    name: "Muffti Backpack 1",
    price: 1499,
    image: "https://via.placeholder.com/200x250?text=Muffti+Backpack+1",
    description: "Durable backpack with multiple compartments.",
    brand: "Muffti",
  },
  {
    id: 396,
    name: "Muffti Backpack 2",
    price: 1599,
    image: "https://via.placeholder.com/200x250?text=Muffti+Backpack+2",
    description: "Stylish and spacious backpack for men.",
    brand: "Muffti",
  },
  {
    id: 397,
    name: "Muffti Casual Shoes 1",
    price: 2599,
    image: "https://via.placeholder.com/200x250?text=Muffti+Shoes+1",
    description: "Comfortable casual shoes for outings.",
    brand: "Muffti",
  },
  {
    id: 398,
    name: "Muffti Casual Shoes 2",
    price: 2699,
    image: "https://via.placeholder.com/200x250?text=Muffti+Shoes+2",
    description: "Trendy and comfortable casual shoes.",
    brand: "Muffti",
  },
  {
    id: 399,
    name: "Muffti Trousers 1",
    price: 1999,
    image: "https://via.placeholder.com/200x250?text=Muffti+Trousers+1",
    description: "Smart casual trousers for men.",
    brand: "Muffti",
  },
  {
    id: 400,
    name: "Muffti Trousers 2",
    price: 2099,
    image: "https://via.placeholder.com/200x250?text=Muffti+Trousers+2",
    description: "Modern fit casual trousers.",
    brand: "Muffti",
  }
];
